improvement; * move most of the "after_success" to "script"              * enable error handling

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -35,7 +35,7 @@ before_install:
 install:
 #  - ln -s $PWD /usr/local/share/arduino/libraries/Adafruit_FONA
 #  - arduino --install-library "Adafruit SleepyDog Library,Adafruit MQTT Library"
-  - arduino --install-library "OneWireHub"
+  - arduino --install-library "OneWireHub,SeeedGrayOLED"
   - source ~/virtualenv/python2.7/bin/activate
   - python --version
   #- pip install -r requirements.txt
@@ -45,12 +45,12 @@ install:
   - deactivate
 
 script:
+  - set -o pipefail  # error in case 'diff' sees differences (get 1st error in pipe), use '+o' to disable/unset
   #- ls -la
-  #- set -o pipefail  # error in case 'diff' sees differences (get 1st error in pipe), use '+o' to disable/unset
   # Uno_OWSlave/OWH_DS2433_EEPROM_LCD_Sensors
   - FILE=$PWD/Uno_OWSlave/OWH_DS2433_EEPROM_LCD_Sensors/OWH_DS2433_EEPROM_LCD_Sensors.ino
-#NEW - issue
-  - arduino --verify --board arduino:avr:uno --verbose --preserve-temp-files $FILE || true  >> $FILE.compile
+#NEW - issue; SeeedGrayOLED missing
+  - arduino --verify --board arduino:avr:uno --verbose --preserve-temp-files $FILE  >> $FILE.compile
   #- astyle  --style=allman  --indent=spaces=4  --verbose  $FILE; diff -u ${FILE}.orig $FILE | tee /dev/stderr | diffstat  # allman=ansi
   - astyle  --style=allman  --indent=spaces=4  --verbose  $FILE  >> $FILE.style; diff -u ${FILE}.orig $FILE | tee -a $FILE.style | diffstat >> $FILE.style  # allman=ansi
   #- astyle  --style=horstmann  --indent=spaces=4  --verbose  $FILE  >> $FILE.style; diff -u ${FILE}.orig $FILE | tee -a $FILE.style | diffstat >> $FILE.style
@@ -58,12 +58,12 @@ script:
   # Yun_N64_Controller_Pak_Reader
   - FILE=$PWD/Yun_N64_Controller_Pak_Reader/Yun_N64_Controller_Pak_Reader.ino
 #NEW
-  - arduino --verify --board arduino:avr:yun --verbose --preserve-temp-files $FILE || true  >> $FILE.compile
+  - arduino --verify --board arduino:avr:yun --verbose --preserve-temp-files $FILE  >> $FILE.compile
   - astyle  --style=kr  --indent=spaces=2  --verbose  $FILE  >> $FILE.style; diff -u ${FILE}.orig $FILE | tee -a $FILE.style | diffstat >> $FILE.style
   # MultiWii_2_4/MultiWii
   - FILE=$PWD/MultiWii_2_4/MultiWii/MultiWii.ino
   #- mkdir $PWD/src && ln -s $FILE $PWD/src/sketch.ino && ino build -m uno && readelf -a $PWD/.build/uno/firmware.elf || true
-  - arduino --verify --board $BOARD --verbose --preserve-temp-files $FILE || true  >> $FILE.compile
+  - arduino --verify --board $BOARD --verbose --preserve-temp-files $FILE  >> $FILE.compile
 #NEW
   - ELF_FILE=`find /tmp/ -name "MultiWii.ino.elf"`
   - readelf -a $ELF_FILE  >> $FILE.info
@@ -84,18 +84,10 @@ script:
 #NEW - issue
   - flake8 --statistics --benchmark --max-complexity=12 --ignore=E127,E221 $FILE || true  >> $FILE.style
   - deactivate
-
-after_success:
-  - FILE=$PWD/MultiWii_2_4/MultiWii/MultiWii.ino
-  - export ELF_FILE=`find /tmp/ -name "MultiWii.ino.elf"`
-  - readelf -a $ELF_FILE  >> $FILE.info
-  #- objdump -x $ELF_FILE
-  #- nm $ELF_FILE || true
-  - strings -d $ELF_FILE  >> $FILE.info
-  - size $ELF_FILE  >> $FILE.info
   # doxygen docu generation
   - doxygen Doxyfile
   #- pushd $PWD/doc/latex/; make; popd
+# push here anyway no matter how many errors - re-enable errors
   # push result back to git repo
   - git checkout -b result/docu
   #- git add $PWD/doc/
@@ -106,6 +98,28 @@ after_success:
   - git config user.name 'Travis CI'
   - git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
   - git push -f https://$GIT_USER:$GIT_PASS@github.com/drtrigon/sketchbook.git result/docu  # dangerous; overwrite remote branch!
+
+after_success:
+#  - FILE=$PWD/MultiWii_2_4/MultiWii/MultiWii.ino
+#  - export ELF_FILE=`find /tmp/ -name "MultiWii.ino.elf"`
+#  - readelf -a $ELF_FILE  >> $FILE.info
+#  #- objdump -x $ELF_FILE
+#  #- nm $ELF_FILE || true
+#  - strings -d $ELF_FILE  >> $FILE.info
+#  - size $ELF_FILE  >> $FILE.info
+#  # doxygen docu generation
+#  - doxygen Doxyfile
+  #- pushd $PWD/doc/latex/; make; popd
+#  # push result back to git repo
+#  - git checkout -b result/docu
+#  #- git add $PWD/doc/
+## exclude .pyc
+#  - git add --all
+#  - git status
+#  - git config user.email 'travis@travis-ci.org'
+#  - git config user.name 'Travis CI'
+#  - git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
+#  - git push -f https://$GIT_USER:$GIT_PASS@github.com/drtrigon/sketchbook.git result/docu  # dangerous; overwrite remote branch!
   # trigger docker-sketchbook (same tests based on docker-arduino)
   - |-
     if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]] ; then
